<?php
defined( 'ABSPATH' ) or die( 'No script kiddies please!' );

/**
 * Check if WooCommerce is active
 * @package melhorenvio
 * @category Integration
 * @author Vítor Soares
 */


if (! class_exists('MelhorEnvioIntegration')):

class MelhorEnvioIntegration  extends WC_Integration
{

    /**
     * MelhorEnvio constructor.
     * @access public
     * @return void
     */

    public function __construct()
    {

        global $woocommerce;

        $this->id = 'melhorenvio';
        $this->method_title = __('Melhor Envio', 'melhorenvio');
        $this->method_description = __('Um modo de integração que mostra para o cliente final o cálculo do seu frete no Melhor Envio.');

        $this->init_form_fields();
        $this->init_settings();

        $this->api_key = $this->get_option('api_key');
        $this->debug = $this->get_option('debug');


		add_action('woocommerce_update_options_integration_' .  $this->id, array( $this, 'process_admin_options' ) );
    }

    public function init_form_fields()
    {
        $this->form_fields = array(
            'api_key' => array(
                'title'         => __('API Key', 'melhorenvio'),
                'type'          => 'text',
                'description'   => __('Digite a sua chave de API que é encontrada no menu de Usuário DropDown no canto direito','melhorenvio'),
                'desc_tip'      => true,
                'default'       => ''
            ),
        'debug' => array(
        'title'             => __( 'Debug Log', 'woocommerce-integration-demo' ),
        'type'              => 'checkbox',
        'label'             => __( 'Enable logging', 'woocommerce-integration-demo' ),
        'default'           => 'no',
        'description'       => __( 'Log events such as API requests', 'woocommerce-integration-demo' ),
    ));
        parent::init_form_fields(); // TODO: Change the autogenerated stub
    }
}

endif;